# Generated by Django 3.0.5 on 2020-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
