# Generated by Django 3.0.5 on 2020-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afront', '0002_human_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='company',
        ),
        migrations.RemoveField(
            model_name='human',
            name='salary',
        ),
        migrations.AddField(
            model_name='human',
            name='gender',
            field=models.CharField(choices=[('man', 'мужчина'), ('unman', 'женщина')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='phone',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
