# Generated by Django 3.0.5 on 2020-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afront', '0003_auto_20200417_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
