# Generated by Django 3.0.5 on 2020-04-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afront', '0005_auto_20200420_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiorythmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('calculate_date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afront.Human')),
            ],
        ),
    ]
