# Generated by Django 3.0.5 on 2020-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afront', '0007_auto_20200421_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biorythmsmodel',
            name='birth_date',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='biorythmsmodel',
            name='calculate_date',
            field=models.SmallIntegerField(),
        ),
    ]
