# Generated by Django 3.0.5 on 2020-04-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afront', '0008_auto_20200421_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biorythmsmodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afront.Human'),
        ),
    ]
