# Generated by Django 3.0.5 on 2020-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afront', '0010_auto_20200422_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='biorythmsmodel',
            name='intel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biorythmsmodel',
            name='mind',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biorythmsmodel',
            name='phys',
            field=models.FloatField(default=0),
        ),
    ]
