# Generated by Django 3.0.5 on 2020-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afront', '0011_auto_20200422_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biorythmsmodel',
            name='birth_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='biorythmsmodel',
            name='calculate_date',
            field=models.CharField(max_length=10),
        ),
    ]
